SELECT * FROM HOS_HOSPITAL;

SELECT * FROM HOS_ENFERMARIA;

SELECT * FROM FCO_FUNCIONARIO;

SELECT * FROM FCO_CARGO;

SELECT * FROM PAC_PACIENTE;

SELECT * FROM PAC_ESTADO_CIVIL;

SELECT * FROM PAC_ACOMPANHANTE;
